version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:274201610284:task-definition/authorization-service:10"
        LoadBalancerInfo:
          ContainerName: "pensioncontainer"
          ContainerPort: "80"
        PlatformVersion: "LATEST"